class MockCObj():
    def __init__(self,
            ord: int = 0,
            provider: str = "CUDA",
            index: int = 0,
            name: str = "MockDevice",
            major: int = 1,
            minor: int = 2,
            total_memory: int = 8*1024**3,
            sms_count: int = 12,
            sm_threads: int = 2048,
            sm_shared_memory: int = 16*1024,
            sm_registers: int = 512,
            sm_blocks: int = 4,
            block_threads: int = 1024,
            block_shared_memory: int = 8*1024,
            block_registers: int = 256,
            warp_size: int = 32,
            l2_cache_size: int = 8*1024**2,
            concurrent_kernels: bool = True,
            async_engines_count: int = 0,
            cooperative: bool = True,
        ) -> None:
        self.ord = ord
        self.provider = provider
        self.index = index
        self.name = name
        self.major = major
        self.minor = minor
        self.total_memory = total_memory
        self.sms_count = sms_count
        self.sm_threads = sm_threads
        self.sm_shared_memory = sm_shared_memory
        self.sm_registers = sm_registers
        self.sm_blocks = sm_blocks
        self.block_threads = block_threads
        self.block_shared_memory = block_shared_memory
        self.block_registers = block_registers
        self.warp_size = warp_size
        self.l2_cache_size = l2_cache_size
        self.concurrent_kernels = concurrent_kernels
        self.async_engines_count = async_engines_count
        self.cooperative = cooperative
