class Properties:
    ord: int
    uuid: str
    provider: str
    index: int
    name: str
    major: int
    minor: int
    total_memory: int
    sms_count: int
    sm_threads: int
    sm_shared_memory: int
    sm_registers: int
    sm_blocks: int
    block_threads: int
    block_shared_memory: int
    block_registers: int
    warp_size: int
    l2_cache_size: int
    concurrent_kernels: bool
    async_engines_count: int
    cooperative: bool

def checkcuda() -> str: ...
def checkamd() -> str: ...
def count() -> int: ...
def _cuda_count() -> int: ...
def _amd_count() -> int: ...
def get(index: int, /) -> Properties: ...
def _nvml_utilisation(index: int, /) -> int: ...
def _nvml_used_memory(index: int, /) -> int: ...
def _nvml_pids(index: int, /) -> list[int]: ...
def _amdsmi_utilisation(index: int, /) -> int: ...
def _amdsmi_used_memory(index: int, /) -> int: ...
def _amdsmi_pids(index: int, /) -> list[int]: ...
def _amdsmi_gfx(index: int, /) -> str: ...
def _amdsmi_drm(index: int, /) -> int: ...
def _amdsmi_node_id(index: int, /) -> int: ...
