class Properties:
    ord: int
    uuid: str
    provider: str
    index: int
    name: str
    major: int
    minor: int
    total_memory: int

def checkcuda() -> str | None: ...
def checkamd() -> str | None: ...
def count() -> int: ...
def get(index: int, /) -> Properties: ...
def nvml_utilisation(index: int, /) -> int: ...
def nvml_used_memory(index: int, /) -> int: ...
def nvml_pids(index: int, /) -> list[int]: ...
def _set_location_hints(locs: list[bytes], /) -> None: ...
def _get_max_hints() -> int: ...
def _get_max_hint_len() -> int: ...
